### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by lzfelix** [ines/spacymoji#4]
Hi, thanks for the awesome add-on to spacy!
Well, I can't install it via `pip install spacymoji` as described in the readme, since this causes me the following error (I am using Python 3.6 and my current spacy version is 2.0.1):

```
>  pip install spacymoji
Collecting spacymoji
  Using cached https://files.pythonhosted.org/packages/3d/be/0074c90f82a38dbb3b4238f7b08de59a5b782ea1b5d8e15b2ce61db8b5a5/spacymoji-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o1doktg0/spacymoji/setup.py", line 42, in <module>
        setup_package()
      File "/tmp/pip-install-o1doktg0/spacymoji/setup.py", line 37, in setup_package
        zip_safe=False,
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/distutils/dist.py", line 971, in run_command
        log.info("running %s", command)
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/distutils/log.py", line 44, in info
        self._log(INFO, msg, args)
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/distutils/log.py", line 32, in _log
        encoding = stream.encoding
      File "/home/lzfelix/bin/miniconda2/envs/dev/lib/python3.6/codecs.py", line 408, in __getattr__
        return getattr(self.stream, name)
    AttributeError: '_io.BufferedWriter' object has no attribute 'encoding'
```

Thanks!

**Comment by ines** [comment]
Just pushed a new version – coud you try again?
